export interface IRegistro {
    id_usuario: number,
    nombre_contacto: string,
    puesto_contacto: string,
    correo_contacto: string,
    nombre_responsable: string,
    correo_responsable: string,
    nombre_empresa: string,
    sitio_web: string,
    telefono_principal: string,
    telefono_secundario: string,
    direccion: string,
    estado: string,
    pais_empresa: string,
    cobertura_mercado: string,
    descripcion_breve: string,
    descripcion_completa: string,
    tipo_mencion: string,
    metodo_pago: string,
    id_transaccion: string,
    autorizado: number,
    logo_empresa: any,
    categorias: [],
    subcategorias: []
}